build:
  environment:
    python:
      version: stackless-3.8
      virtualenv: true
  dependencies:
    override::
      - pip install -r requirements.txt -r requirements-dev.txt
  tests:
    override:
      - command: 'pytest --cov'
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'
