version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pip install flake8 pytest
          name: Install requirements
      - run:
          command: pip install -e .
          name: Build and Install
      - run:
          command: pytest
          name: Test
          environment:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          

workflows:
  main:
    jobs:
      - build-and-test
